### ISSUE TITLE
QQ一切正常，但乱码问题无法解决

### ISSUE THREAD

**Issue by MomentDerek** [Hackerl/Wine_Appimage#10]
![2018-07-07 18-24-08](https://user-images.githubusercontent.com/40252940/42409934-3a87690e-8214-11e8-8805-ddb5c46b9c4e.png)
除了乱码，其他的一切都十分完美
系统是Ubuntu18.04 之前装过wine但是已经完全卸载干净，重新清理了appimage产生的文件后再打开，仍然乱码
顺便问问第一次运行的时候要我装的那个wine mono，有影响吗，我没有装

**Comment by Hackerl** [comment]
稍等，我装个Ubuntu18测试一下，我在很多虚拟机里面测试都没乱码。wine mono是.Net环境，不装没关系。还有，能否在命令行下运行，并提供输出。能否测试一下别的软件，迅雷、微信等等，看是否由乱码。

**Comment by Hackerl** [comment]
我在虚拟机下测试的确乱码了，我查查原因.

**Comment by Hackerl** [comment]
可能ubuntu没有安装truetype字体，尝试运行 sudo apt install ubuntu-restricted-extras，会安装mp4解码器以及windows字体等.

**Comment by Hackerl** [comment]
我手动复制truetype字体，解决了乱码问题
![screenshot from 2018-07-08 13-08-53](https://user-images.githubusercontent.com/15811751/42417021-3d977d90-82b0-11e8-9ca0-438f8b46acd1.png)

**Comment by MomentDerek** [comment]
好的，我去试试

**Comment by MomentDerek** [comment]
依旧不行，乱码换了一种款式。
已经下载了另外的几款appimage，也是乱码
能告诉我你是怎么手动复制的吗，可能是他安装的字体包的问题（只有英文字体，没有中文字体）
因为我已经能够看到qq这几个字了，就是在qq账号输入框内，qq+6个框框（应该是两个中文？）
忘记截图了

**Comment by MomentDerek** [comment]
哦。。。看了之前的截图，发现也有qq两个字，只是我现在和之前的截图比较，密码输入框的三条|||变成 三个框框

**Comment by MomentDerek** [comment]
看了之前的截图，好像一样。。。。方了

**Comment by Hackerl** [comment]
安装一下文泉驿字体 sudo apt-get install fonts-wqy-microhei

**Comment by MomentDerek** [comment]
搞定了，一阵舒爽

**Comment by MomentDerek** [comment]
不过好像没法在里面打中文

**Comment by Hackerl** [comment]
没法输入是无法调用输入法，还是输入法输出的是乱码。
还有是什么输入法，ibus还是fcitx?

**Comment by MomentDerek** [comment]
fcitx，无法调用中文输入法，只能输入英文

**Comment by Hackerl** [comment]
可以用复制粘贴代替一下，我查查原因

**Comment by lgsen1996** [comment]
输入法问题解决了吗？我遇到同样的问题了，也是使用的fcitx，无法调用搜狗输入法，只能输入英文

**Comment by Walstruzz** [comment]
你好，
Ubuntu 18.04 
Gnome3 
iBus  Chinese(Intelligent Pinyin)
安装完文泉驿字体后乱码问题解决了，迅雷和QQ账号可以粘贴，密码无法输入。
请问需要怎么解决，感谢～

**Comment by Hackerl** [comment]
ubuntu版本已发布，修复了输入法问题 -- https://github.com/Hackerl/Wine_Appimage/releases/download/v2.0/Wine-3.10-ubuntu-x86_64.AppImage

![image](https://user-images.githubusercontent.com/15811751/50679152-303f1200-103d-11e9-9d0a-a4976d8c9362.png)

**Comment by holazt** [comment]
@Hackerl ibus-rime 输入法支持吗？

**Comment by Hackerl** [comment]
> @Hackerl ibus-rime 输入法支持吗？

没测过，只测了fcitx

**Comment by Hackerl** [comment]
@ZetaoYang 测过了，可以使用

**Comment by holazt** [comment]
@Hackerl ibus-rime 还是不能输入中文。

**Comment by Hackerl** [comment]
> @Hackerl ibus-rime 还是不能输入中文。

@ZetaoYang 你是什么系统环境，wine使用的是xim，各个发行版的libxi有差异，会导致无法输入。
我目前针对ubuntu、debian、majaro各打包了一个版本，都测试通过了。
这个问题还是比较难解决，打包的wine在各个平台都能运作，但是输入法的问题不能一次性解决。

**Comment by holazt** [comment]
@Hackerl Fedora 29 Gnome Wayland ibus-rime. 使用 debian 版本的 wine appimage

**Comment by Hackerl** [comment]
> @Hackerl Fedora 29 Gnome Wayland ibus-rime. 使用 debian 版本的 wine appimage

要不你试试另外两个，改变wine的链接即可。
我是debian 9系统，所以打包用的deb都比较旧。
ubuntu与manjaro的包都比较新，我交叉试过这两个，输入法都没问题。
如果每个发行版都打包一个版本，工作量有点大。

**Comment by Hackerl** [comment]
另外还需要检查一下xim环境变量"XMODIFIERS"是否设置正确
```
printenv |grep XMODIFIERS
```
正常应该输出:
```
XMODIFIERS=@im=ibus
```

**Comment by holazt** [comment]
@Hackerl 
![image](https://user-images.githubusercontent.com/10769951/50736802-c8372a00-11fc-11e9-9d6d-0c6d552caf3c.png)

**Comment by Hackerl** [comment]
@ZetaoYang 有试过其他两种吗，如果不行，我找时间打包一个Fedora的版本。
https://github.com/Hackerl/Wine_Appimage/releases/tag/v2.0

**Comment by holazt** [comment]
@Hackerl 只有 ubuntu 版本的可以 输入中文(ibus-rime)。 刚试过

**Comment by Hackerl** [comment]
> @Hackerl 只有 ubuntu 版本的可以 输入中文(ibus-rime)。 刚试过

那就好，libxi的差异还是很难解决。
appimage使用打包的lib，而输入法使用的本地lib。

**Comment by holazt** [comment]
@Hackerl 能不能通过 CI 自动打包 wine 环境， docker 提供不同 linux 发行版支持？

**Comment by Hackerl** [comment]
我现在是通过包管理直接下载的依赖lib，因为可以省略编译和配置的过程。
wine依赖于:
> lib32-acl lib32-attr lib32-bzip2 lib32-expat lib32-fontconfig lib32-freetype2 lib32-gcc-libs lib32-gettext lib32-glib2 lib32-glibc lib32-glu lib32-harfbuzz lib32-icu lib32-lcms2 lib32-libcap lib32-libdrm lib32-libelf lib32-libffi lib32-libgcrypt lib32-libglvnd lib32-libgpg-error lib32-libice lib32-libjpeg-turbo lib32-libnl lib32-libpcap lib32-libpciaccess lib32-libpng lib32-libsm lib32-libtiff lib32-libusb lib32-libx11 lib32-libxau lib32-libxcb lib32-libxcursor lib32-libxdamage lib32-libxdmcp lib32-libxext lib32-libxfixes lib32-libxi lib32-libxml2 lib32-libxrandr lib32-libxrender lib32-libxshmfence lib32-libxxf86vm lib32-llvm-libs lib32-lm_sensors lib32-lz4 lib32-mesa lib32-ncurses lib32-pcre lib32-readline lib32-systemd lib32-util-linux lib32-wayland lib32-xz lib32-zlib lib32-zstd

各个发行版的包管理是不同的，通过CLI构建只能编译各个库，而且编译的libxi也不能通用。
通过docker的实现已经有了，我之所以选择appimage打包，是因为比docker更加轻量。
否则想使用软件，还得安装docker，普通用户可能无法接受。
如果使用docker，文件系统完全隔离，也就没有ld.so等问题了，但是docker中的libxi也可能无法与宿主系统兼容。

**Comment by holazt** [comment]
> 我现在是通过包管理直接下载的依赖lib，因为可以省略编译和配置的过程。
> wine依赖于:
> 
> > lib32-acl lib32-attr lib32-bzip2 lib32-expat lib32-fontconfig lib32-freetype2 lib32-gcc-libs lib32-gettext lib32-glib2 lib32-glibc lib32-glu lib32-harfbuzz lib32-icu lib32-lcms2 lib32-libcap lib32-libdrm lib32-libelf lib32-libffi lib32-libgcrypt lib32-libglvnd lib32-libgpg-error lib32-libice lib32-libjpeg-turbo lib32-libnl lib32-libpcap lib32-libpciaccess lib32-libpng lib32-libsm lib32-libtiff lib32-libusb lib32-libx11 lib32-libxau lib32-libxcb lib32-libxcursor lib32-libxdamage lib32-libxdmcp lib32-libxext lib32-libxfixes lib32-libxi lib32-libxml2 lib32-libxrandr lib32-libxrender lib32-libxshmfence lib32-libxxf86vm lib32-llvm-libs lib32-lm_sensors lib32-lz4 lib32-mesa lib32-ncurses lib32-pcre lib32-readline lib32-systemd lib32-util-linux lib32-wayland lib32-xz lib32-zlib lib32-zstd
> 
> 各个发行版的包管理是不同的，通过CLI构建只能编译各个库，而且编译的libxi也不能通用。
> 通过docker的实现已经有了，我之所以选择appimage打包，是因为比docker更加轻量。
> 否则想使用软件，还得安装docker，普通用户可能无法接受。

我的意思是 用 docker 自动化打包 appimage

**Comment by Hackerl** [comment]
这个可以实现，需要针对各个发行版的包管理编写构建脚本。

**Comment by Sakura-Mukira** [comment]
https://github.com/Hackerl/Wine_Appimage/issues/10#issuecomment-403361572
感谢
