### ISSUE TITLE
elementray os 0.4.1运行不了，命令行有报错提示。

### ISSUE THREAD

**Issue by qq420100523** [Hackerl/Wine_Appimage#12]
`/tmp/.mount_TIM-x8TKFuNF/AppRun:行23: /tmp/.mount_TIM-x8TKFuNF/usr/bin/wine: 没有那个文件或目录
Cleaning up
`

**Comment by Hackerl** [comment]
这个不是我这个项目吧，我的项目打包里面没有/usr/bin/wine，你是否使用的 https://github.com/askme765cs/Wine-QQ-TIM 项目文件?
这个问题我已经提交了issue -- https://github.com/askme765cs/Wine-QQ-TIM/issues/86.
你可以下载使用我打包的wine与TIM.
