### ISSUE TITLE
新手安装出现问题,大佬指点下

### ISSUE THREAD

**Issue by naturalCloud** [Hackerl/Wine_Appimage#14]
![_ _20180730132056](https://user-images.githubusercontent.com/30367263/43378763-7052b694-93fb-11e8-8a11-0389870493a0.png)

**Comment by Hackerl** [comment]
不要使用wine64 appimage，使用wine appimge

**Comment by naturalCloud** [comment]
装了你说的可以运行了,但是输入不了中文怎么破?先谢过大佬

**Comment by naturalCloud** [comment]
![image](https://user-images.githubusercontent.com/30367263/43396541-789a8cee-9434-11e8-8968-b879bc951360.png)
这个错误

**Comment by Hackerl** [comment]
这不是错误，你什么系统

**Comment by naturalCloud** [comment]
乌班图 18.04

**Comment by Hackerl** [comment]
好像ubuntu都有这个问题，我有空看看

**Comment by naturalCloud** [comment]
使用了deepin-wine 的移植解决了日常沟通问题,不过要感谢作者的开源

**Comment by Hackerl** [comment]
最新版已经针对各个发行版解决了输入法问题
