### ISSUE TITLE
微信更新后无法正常启动，报错找不到更新包

### ISSUE THREAD

**Issue by younglovej** [Hackerl/Wine_Appimage#15]
咨询一个微信更新的问题
更新后重启，找不到更新包，没办法启动
还请知道如何修改路径找到对应的更新路径？

或者说怎么清理以下wine的配置？我重装用旧的微信

错误信息如下：
wine: cannot find L"c:\\Program Files\\Tencent\\WeChat\\WeChatUpdate.exe"
wine: cannot find L"c:\\Program Files\\Tencent\\WeChat\\WeChatUpdate.exe"
Wine Cleaning up
Cleaning up

谢谢！

**Comment by Hackerl** [comment]
不要更新，之后我会更新appimage，删除 $Home/.Wechat 文件夹，然后重新运行。

**Comment by younglovej** [comment]
删除 $Home/.Wechat 文件夹之后可以继续使用了

但我还是想问问，如果能让启动找到c:\Program Files\Tencent\WeChat\WeChatUpdate.exe
是不是就可以正常更新了？

**Comment by Hackerl** [comment]
这个文件是有的，但是在wine下跑不起来，你可以看看 $HOME/.Wechat/drive_c/Program Files/Tencent/WeChat/WeChatUpdate.exe

**Comment by younglovej** [comment]
明白了，谢谢

另外如果我想添加一个桌面快捷方式，图标也换成微信的话，可以怎么做？
现在我是直接命令行运行来启动的。。。

**Comment by Hackerl** [comment]
参考你桌面环境的.desktop文件，建一个.desktop，换成微信图标，执行路径指向appimage

**Comment by younglovej** [comment]
我查看了一下其他.desktop快捷方式，其实Icon应该是图标，这个图标要写成什么才可以换成为微信图标？

谢谢！

**Comment by Hackerl** [comment]
下个微信的png，然后icon设成png路径
