### ISSUE TITLE
微信显示字体异常

### ISSUE THREAD

**Issue by suinxinliulang** [Hackerl/Wine_Appimage#16]
我安装好微信后不能显示汉字
![2018-09-13 19-53-13](https://user-images.githubusercontent.com/37922670/45486743-c6011980-b78e-11e8-8d2c-2b97f8877f37.png)

**Comment by Hackerl** [comment]
https://github.com/Hackerl/Wine_Appimage/issues/10
参考这个

**Comment by suinxinliulang** [comment]
> #10
> 参考这个

解决了 感谢
