### ISSUE TITLE
迅雷极速版，用几次就会出现:磁盘不可写，选的目录就不能用了

### ISSUE THREAD

**Issue by WeihuaGu** [Hackerl/Wine_Appimage#17]
开始选定的那个目录就没法子写入了,选目录时那个文件夹就变成了白色。目录确定有写入权限。

**Comment by Hackerl** [comment]
这个问题可能比较难处理，wine的移植本来就不是很完善，你可以试试迅雷精简版，问题比较少。

**Comment by WeihuaGu** [comment]
@Hackerl 好的，感谢：）
