### ISSUE TITLE
ThunderMini显示乱码

### ISSUE THREAD

**Issue by hp7hao** [Hackerl/Wine_Appimage#19]
我安装了ThunderMini，但是界面是乱码
安装wqy字体没有效果，我把simsun.ttf拷贝到 ~/.ThunderMini/drive_c/windows/Fonts下面之后，能显示出部分字体，不过还有一部分字体无法显示

![screenshot_20181111_224929](https://user-images.githubusercontent.com/9319235/48314475-06e9a300-e605-11e8-97fa-c0d857d3d2b9.png)

请问需要手动拷贝那些字体？
（我的系统是kde neon 基于ubuntu18.04的版本）

**Comment by Hackerl** [comment]
安装了文泉驿不应该还乱码的，执行了这个吗?
```bash
sudo apt-get install fonts-wqy-microhei
```
https://github.com/Hackerl/Wine_Appimage/issues/10

**Comment by hp7hao** [comment]
是我装错了wqy的包，装成了正黑，感谢！

**Comment by probonopd** [comment]
```
me@host:~$ Downloads/ThunderMini-x86_64.AppImage 
wine: Unhandled page fault on read access to 0x0000002c at address 0x7bc411a9 (thread 0014), starting debugger...
p11-kit: couldn't load module: /usr/lib/i386-linux-gnu/pkcs11/p11-kit-trust.so: /usr/lib/i386-linux-gnu/pkcs11/p11-kit-trust.so: cannot open shared object file: No such file or directory
```

**Comment by jactry** [comment]
Hi，

> 安装了文泉驿不应该还乱码的，执行了这个吗?
> 
> ```shell
> sudo apt-get install fonts-wqy-microhei
> ```
> 
> #10

也许可以通过给 Wine 的注册表的 font replacements（HKCU\\Software\\Wine\\Fonts\\Replacements），给 SimSun 等这些常用 Windows 中文字体设置一个 REG_MULTI_SZ replacement 来尽可能通用地解决这个问题。REG_MULTI_SZ 可以写入多个字体名称，这样如果把 Ubuntu、Fedora 的默认中文字体及其他常用中文字体都写入的话，Wine 就会依次去找到本机有安装的那个字体，然后使用。

**Comment by Hackerl** [comment]
最新版已内置中文字体
