### ISSUE TITLE
可以构建一个RTX 2015的AppImage吗?

### ISSUE THREAD

**Issue by lexusking** [Hackerl/Wine_Appimage#20]
你好,按照wiki上的说明,还是不懂如何构建一个windows appImage. 可以把构建的步骤写得详细一点吗?
另外,请问你是在deepin 这些系统上已经安装好了一个软件,比如迅雷, 然后基于这个安装好的软件目录做构建吗?
因为构建windows appImage的源,我不清楚是从哪里来的.

最后,楼主方便的话,可以构建一个RTX 的appImage 共享上来吗?

 谢谢了.

**Comment by Hackerl** [comment]
我尝试了一下，跑不起来，不过企业微信我跑起来了。
