### ISSUE TITLE
不需要 Mono, Gecko

### ISSUE THREAD

**Issue by probonopd** [Hackerl/Wine_Appimage#22]
Please change WINE to not do this
请改变WINE不要这样做

![](https://user-images.githubusercontent.com/2480569/49695168-0fe37b00-fb97-11e8-9620-fc9ef47c6050.png)

![](https://user-images.githubusercontent.com/2480569/49695169-107c1180-fb97-11e8-8916-706ed792e8d0.png)

**Comment by probonopd** [comment]
```
export WINEDLLOVERRIDES="mscoree,mshtml="
```

**Comment by Hackerl** [comment]
谢谢你的解决方案

---

Thank you for your solution
