### ISSUE TITLE
请将中文字体放入AppImage中

### ISSUE THREAD

**Issue by probonopd** [Hackerl/Wine_Appimage#23]
请将中文字体放入WINE AppImage中。
Please put Chinese fonts in the AppImage.

![](https://user-images.githubusercontent.com/2480569/49695224-132b3680-fb98-11e8-9ebf-5aed3fcd02f2.png)

更多信息
More information
https://github.com/AppImage/AppImageKit/issues/551#issuecomment-347724451

对国际用户有好处。 非常感谢你的出色工作。
Good for international users. Thank you very much for your excellent work.

**Comment by Hackerl** [comment]
The new version of the windows application has built-in Chinese fonts.

https://github.com/Hackerl/Wine_Appimage/releases/tag/appv2.0

**Comment by probonopd** [comment]
Thank you.
