### ISSUE TITLE
QQInternational

### ISSUE THREAD

**Issue by probonopd** [Hackerl/Wine_Appimage#26]
你能为QQInternational制作一个应用程序映像吗？非常感谢。谢谢您。

---

Could you please make an AppImage for QQInternational? Highly appreciated. Thank you.

**Comment by Hackerl** [comment]
我没有太多时间去配置，仅仅做一个示范。

---

I don't have much time to configure, just a demonstration.

test file : https://github.com/Hackerl/Wine_Appimage/releases/tag/test

**Comment by probonopd** [comment]
非常感谢。不幸的是，无法输入密码。当我自己尝试的时候，我也遇到了同样的问题。这是一个众所周知的问题，但我无法得到解决办法的工作。

有了这个应用程序将极大地帮助中国以外的社区成员与中国社区沟通。

---

Thank you very much. Unfortunately it is not possible to enter the password. I had the same problem when I tried on my own. It is a known issue but I could not get the workarounds to work.

Having this application would greatly help community members outside of China communicate with the Chinese community.

**Comment by Hackerl** [comment]
I saw the relevant information, QQ International 2.0 don't have this bug, have you tried it?

**Comment by probonopd** [comment]
谢谢，我已经试过了，但是遇到了不稳定和崩溃。

---

Thank you, I have tried but ran into instabilities and crashes.

**Comment by yinflying** [comment]
国际版无法通过键盘输入密码，但是可以通过软件键操作（且操作过程中无显示）。但是国际版可以记住密码，其对应的密码文件和轻聊版可以通用，故我采用该方法解决了轻聊版无法记住密码的问题。

**Comment by probonopd** [comment]
Thanks @yinflying 

> The international version cannot enter the password via the keyboard, but it can be operated by the software key (and there is no display during the operation). But the international version can remember the password, the corresponding password file and the light chat version can be used universally, so I use this method to solve the problem that the light chat version cannot remember the password.
