### ISSUE TITLE
ubuntu18.04 wetchat 文本框使用搜狗输入法不能输入中文,但是其他地方复制过来的中文可以使用

### ISSUE THREAD

**Issue by NeaoSwift** [Hackerl/Wine_Appimage#28]

**Comment by NeaoSwift** [comment]
![image](https://user-images.githubusercontent.com/12521986/50538416-87ab3100-0baa-11e9-896f-8aef3678ddf7.png)

**Comment by probonopd** [comment]
WeChat-x86_64.AppImage中的内容是在比您运行的系统更新的系统上生成的。你用的是哪个Ubuntu版本？

**Comment by NeaoSwift** [comment]
光标在wechat的输入框中时,可以切换到搜狗输入法,但是搜狗输入法打出的文字没有到输入框内.英文不会出现该问题.

**Comment by NeaoSwift** [comment]
> WeChat-x86_64.AppImage中的内容是在比您运行的系统更新的系统上生成的。你用的是哪个Ubuntu版本？

当前系统Ubuntu18.04

**Comment by probonopd** [comment]
奇怪的错误。你能试试这个链接到`/usr/bin/wine`吗？ 

https://github.com/probonopd/libhookexecv/releases/download/continuous/Wine_Windows_Program_Loader-3.5-x86_64.AppImage

**Comment by NeaoSwift** [comment]
> 奇怪的错误。你能试试这个链接到`/usr/bin/wine`吗？
> 
> https://github.com/probonopd/libhookexecv/releases/download/continuous/Wine_Windows_Program_Loader-3.5-x86_64.AppImage

![image](https://user-images.githubusercontent.com/12521986/50538629-17ea7580-0bad-11e9-9f06-34f4a3c3beec.png)

**Comment by NeaoSwift** [comment]
使用了Wine_Windows_Program_Loader-3.5-x86_64.AppImage作为wine,并不能打开wechat.但是将我跳转到了[https://pc.weixin.qq.com/](url)

**Comment by probonopd** [comment]
对不起，我不知道。也许@hackerl能帮上忙。

**Comment by NeaoSwift** [comment]
> 对不起，我不知道。也许@Hackerl能帮上忙。

同样感谢您的回复,

**Comment by NeaoSwift** [comment]
没有使用 @Hackerl 打包好的wine,直接使用sudo apt-get install wine-stable.然后直接执行wechat.一切正常.感谢 @probonopd 宝贵的时间,以及 @Hackerl 的无私开源精神.这个版本的wechat是linux下面体验最好的版本.

**Comment by NeaoSwift** [comment]
由此也带来了新的问题,由于使用了wine-stable.而不是 @Hackerl [](编译好的[https://github.com/Hackerl/Wine_Appimage/releases/download/zero/Wine-x86_64.AppImage](url) .在下载了TIM-x86_64.AppImage之后,并不能成功的打开TIM.

**Comment by NeaoSwift** [comment]
[https://github.com/Hackerl/Wine_Appimage/releases/download/one/TIM-x86_64.AppImage](url)

**Comment by NeaoSwift** [comment]
![image](https://user-images.githubusercontent.com/12521986/50538990-0a84b980-0bb4-11e9-9953-d994a3051702.png)

**Comment by Hackerl** [comment]
@NeaoSwift  "sudo apt-get install wine-stable"安装的wine能正常输入中文?我打包的appimage不能?
能否告诉我你现在wine的版本。
```bash
wine --version
```
从TIM.Appimage的输出消息看，可能是由于wine版本太低，TIM调用了wine还没有实现的win32 api。

**Comment by NeaoSwift** [comment]
> @NeaoSwift "sudo apt-get install wine-stable"安装的wine能正常输入中文?我打包的appimage不能?
> 能否告诉我你现在wine的版本。
> 
> ```shell
> wine --version
> ```
> 
> 从TIM.Appimage的输出消息看，可能是由于wine版本太低，TIM调用了wine还没有实现的win32 api。

![image](https://user-images.githubusercontent.com/12521986/50577631-046a3380-0e67-11e9-94a6-0fe727e1a953.png)

**Comment by Hackerl** [comment]
> 
> 
> > @NeaoSwift "sudo apt-get install wine-stable"安装的wine能正常输入中文?我打包的appimage不能?
> > 能否告诉我你现在wine的版本。
> > ```shell
> > wine --version
> > ```
> > 
> > 
> > 从TIM.Appimage的输出消息看，可能是由于wine版本太低，TIM调用了wine还没有实现的win32 api。
> 
> ![image](https://user-images.githubusercontent.com/12521986/50577631-046a3380-0e67-11e9-94a6-0fe727e1a953.png)

版本太老了，你使用这个版本可以调用输入法?

**Comment by NeaoSwift** [comment]
是的.貌似没有什么功能缺失

**Comment by Hackerl** [comment]
删除"$HOME/.TIM"，多运行几次试试，貌似TIM有时会起不来。

**Comment by Hackerl** [comment]
ubuntu版本已发布，修复了输入法问题 -- https://github.com/Hackerl/Wine_Appimage/releases/download/v2.0/Wine-3.10-ubuntu-x86_64.AppImage

![image](https://user-images.githubusercontent.com/15811751/50679152-303f1200-103d-11e9-9d0a-a4976d8c9362.png)

**Comment by NeaoSwift** [comment]
@Hackerl 微信，ｔｉｍ，云盘都可以了．谢谢

**Comment by zsien** [comment]
Debisn Sid 用 Fcitx 輸入不了誒（

**Comment by Hackerl** [comment]
@zijung 我只构建了stretch、buster两个版本，我回头补上，其实你可以自己执行构建脚本(https://github.com/Hackerl/Wine_Appimage/blob/master/deployscript/debian-winedeploy.sh) 试试。

https://github.com/Hackerl/Wine_Appimage/releases/tag/continuous 这几个版本你都试过吗?

**Comment by Hackerl** [comment]
@zijung 试一下sid版本 https://github.com/Hackerl/Wine_Appimage/releases/tag/continuous

**Comment by zsien** [comment]
@Hackerl 用 Sid 版 Wine 後，TIM 沒問題了。

但 WeChat 第一次運行打不開也沒有 TIM 打開時「正在更新 /tmp/.TIM.unionfs 中的 Wine 設定」的窗口。
第二次能打開，但提示「無法使用檔案默認存儲位置，導致 WeChat 不能正常使用，請更改位置」，看上去是用戶文件夾沒掛載？
然後還有 ERROR：「ERROR: ld.so: object '/tmp/.mount_wineZm6RES/bin/libhookexecv.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.」

**Comment by Hackerl** [comment]
@zijung 
试试删除 $HOME/.Wechat 文件夹，重新运行Wechat。
如果有错误请截图下来发到这里，我研究一下。

下面这个错误可以忽略，因为我对wine做了一些hook，这个错误不影响
> 「ERROR: ld.so: object '/tmp/.mount_wineZm6RES/bin/libhookexecv.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.」

**Comment by GongSiqiu** [comment]
Debian stretch QQ 输入不了中文
QQ-x86_64.AppImage
Wine-3.10-debian-x86_64.AppImage

**Comment by Hackerl** [comment]
@GongSiqiu 检查一下环境变量 https://github.com/Hackerl/Wine_Appimage/issues/10#issuecomment-451742668
然后试试  https://github.com/Hackerl/Wine_Appimage/releases/tag/continuous 里面的stretch版本

**Comment by zsien** [comment]
嗯，刪除過 $HOME/.Wechat 了，這是截圖
![image](https://user-images.githubusercontent.com/8380597/55125051-6de69f00-5143-11e9-96c9-383f3d2b6770.png)

然後，Home 下會新建「All Users」、「kvcomm」、「log」這仨文件夾

**Comment by GongSiqiu** [comment]
环境变量
![图片](https://user-images.githubusercontent.com/40697840/55134332-7222b480-5163-11e9-92d2-37672d342f64.png)
 https://github.com/Hackerl/Wine_Appimage/releases/tag/continuous 里面的stretch版本依然如此

**Comment by Hackerl** [comment]
@GongSiqiu 我用的就是debian9，输入法一直很正常，你的系统有经常更新吗

**Comment by Hackerl** [comment]
@zijung 请提供一下系统发行版，发行版版本，以及桌面环境。
还有，wechat appimage也是在我的releases里面下载的吗?

**Comment by GongSiqiu** [comment]
有经常更新

**Comment by Hackerl** [comment]
@GongSiqiu 执行一下 "locale" 命令，看看地区设定

**Comment by GongSiqiu** [comment]
![图片](https://user-images.githubusercontent.com/40697840/55152502-824e8a00-518b-11e9-8b8b-65331a83e11e.png)

**Comment by zsien** [comment]
@Hackerl Debian Sid 滾到最新了，桌面是 GNOME，是在這裏下載的 WeChat

**Comment by onism68** [comment]
arch + kde  也遇到了同样的问题

**Comment by onism68** [comment]
./TIM-x86_64.appimage 
wine: Call from 0x7b440b42 to unimplemented function ntoskrnl.exe.FsRtlIsNameInExpression, aborting
wine: Unimplemented function ntoskrnl.exe.FsRtlIsNameInExpression called at address 0x7b440b42 (thread 0034), starting debugger...
ERROR: ld.so: object '/tmp/.mount_wineXEy2ja/bin/libhookexecv.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/tmp/.mount_wineXEy2ja/bin/libhookexecv.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
wine: Call from 0x7b440b42 to unimplemented function ntoskrnl.exe.FsRtlIsNameInExpression, aborting
wine: Unimplemented function ntoskrnl.exe.FsRtlIsNameInExpression called at address 0x7b440b42 (thread 004f), starting debugger...
wine: Call from 0x7b440b42 to unimplemented function ntoskrnl.exe.FsRtlIsNameInExpression, aborting
wine: Unimplemented function ntoskrnl.exe.FsRtlIsNameInExpression called at address 0x7b440b42 (thread 0076), starting debugger...
wine: cannot find L"c:\\Program Files\\Tencent\\TIM\\Bin\\TXPlatform.exe"
Cleaning up

**Comment by Hackerl** [comment]
@onism68 删除 ~/.TIM 文件夹，重新运行

**Comment by onism68** [comment]
我试试，感谢回复，（回复真快）

**Comment by onism68** [comment]
仍旧不可以

**Comment by Hackerl** [comment]
@onism68 请提供系统环境

**Comment by Hackerl** [comment]
@onism68 其他的程序运行正常吗

**Comment by onism68** [comment]
➜  Downloads ./Wechat-x86_64.appimage
ERROR: ld.so: object '/tmp/.mount_wineoMoajn/bin/libhookexecv.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/tmp/.mount_wineoMoajn/bin/libhookexecv.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Cleaning up

**Comment by onism68** [comment]
上面微信打不开，说是缺少WeChatwin.dll
然后这是迅雷，可以打开，但是仍旧是无法输入中文
Downloads ./ThunderMini-x86_64.appimage 
wine: configuration in '/tmp/.ThunderMini.unionfs' has been updated.
ERROR: ld.so: object '/tmp/.mount_winemvYJsD/bin/libhookexecv.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/tmp/.mount_winemvYJsD/bin/libhookexecv.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Cleaning up

**Comment by amazingfate** [comment]
我在用opensuse用arch的appimage无法在tim使用输入法，之前ubuntu和debian是如何修复的，想了解一下思路

**Comment by Hackerl** [comment]
> 
> 
> 我在用opensuse用arch的appimage无法在tim使用输入法，之前ubuntu和debian是如何修复的，想了解一下思路

可以试试自己打包: https://github.com/Hackerl/Wine_Appimage/blob/master/deployscript/arch-winedeploy.sh

**Comment by amazingfate** [comment]
@Hackerl 打了个64m的image，居然能用fcitx了，看来就是系统库版本不一致导致的

**Comment by Hackerl** [comment]
@amazingfate arch更新本来就快，自动打包系统发布的版本都挺久了，自己系统上打包的话就大概率没问题
