### ISSUE TITLE
TIM无法运行

### ISSUE THREAD

**Issue by hnshhslsh** [Hackerl/Wine_Appimage#3]
```
$ ./TIM-x86_64\ .AppImage 
Create ld-linux.so.2
p11-kit: couldn't load module: /usr/lib/i386-linux-gnu/pkcs11/p11-kit-trust.so: /usr/lib/i386-linux-gnu/pkcs11/p11-kit-trust.so: cannot open shared object file: No such file or directory
p11-kit: couldn't load module: /usr/lib/i386-linux-gnu/pkcs11/gnome-keyring-pkcs11.so: /usr/lib/i386-linux-gnu/pkcs11/gnome-keyring-pkcs11.so: cannot open shared object file: No such file or directory
Wine Cleaning up
Cleaning up
```
操作系统是Ubuntu 16.04，已经执行过`sudo ln -s $(pwd)/Wine-3.6-x86_64.AppImage /usr/bin/wine`了，微信可用，但是Tim无法运行。

**Comment by Hackerl** [comment]
你再运行几次看看，貌似有时候会这样，这里没有报任何错误

**Comment by jianglinzhou2003** [comment]
您好，在运行这个版本的TImAppimage的时候出现了以下错误：
wine: '/tmp/.TIM.unionfs' is a 32-bit installation, it cannot support 64-bit applications.
Cleaning up
已经参照百度打开了32位的支持，不知道有没有什么解决方法？谢谢
（Kali linux 3.28.1）

**Comment by Hackerl** [comment]
你是否下载了wine64.appimage，应该使用wine.appimage

**Comment by jianglinzhou2003** [comment]
不好意思前段时间中考没有弄，已经成功运行TIm，谢谢！

**Comment by Hackerl** [comment]
我已经更新了所有appimage，你可以试试新的，会有更好的体验
