### ISSUE TITLE
迅雷开启后左上角无法覆盖

### ISSUE THREAD

**Issue by YaoLaiGang** [Hackerl/Wine_Appimage#31]
![2019-01-31 17-17-31](https://user-images.githubusercontent.com/15951265/52045416-74133180-257f-11e9-99af-14a9839ea7e8.png)
写的比较仓促，大体情况就像上图所示，左上角会出现这种奇怪的情况，我猜测是不是悬浮球一类的东西无法显示造成的bug

**Comment by Hackerl** [comment]
这个bug我也有遇到，但是是应用本身造成的，比较难修复。那个方块好像是一个窗口，你可以试试把那个窗口拖到另外一个工作桌面，看能不能隐藏掉。

**Comment by Hackerl** [comment]
如果没有磁力链接下载的需求，可以使用迅雷精简版，因为精简版应用本身简单，所以wine运行出bug的几率小。

**Comment by YaoLaiGang** [comment]
> 如果没有磁力链接下载的需求，可以使用迅雷精简版，因为精简版应用本身简单，所以wine运行出bug的几率小。

这个bug影响也不是很大，十分感谢作者的打包开发
