### ISSUE TITLE
QQLight TIM 部分图无法加载

### ISSUE THREAD

**Issue by bigshans** [Hackerl/Wine_Appimage#32]
非常奇怪的问题，因为这两个应用一开始都能正常显示，然后某一次打开之后就有一部分图就不能正常显示了。有什么办法解决吗？

**Comment by Hackerl** [comment]
有截图给我看看吗?

**Comment by bigshans** [comment]
我早上折腾一下，把 crossover 的 tim 提了出来，然后又突然好使了。我把 crossover 的移动掉，再运行 appimage 貌似又好了。不知道什么原因。之前用 deepin-qq 和 deepin-tim 的时候也是这个问题，一直没有解决。不清楚什么原因。
就是一部分图显示需要点击加载，但点击了也无法加载。
