### ISSUE TITLE
迅雷 

### ISSUE THREAD

**Issue by WarlockFish** [Hackerl/Wine_Appimage#33]
wine: cannot find 'c:\Program Files\Thunder Network\MiniThunder\Bin\ThunderMini.exe'
Cleaning up

之前还是可以的,忽然不可以了

**Comment by Hackerl** [comment]
删除"~/.ThunderMini"文件夹，重新运行

**Comment by WarlockFish** [comment]
谢谢,删除后重新运行就可以了,谢谢
