### ISSUE TITLE
没启动起来

### ISSUE THREAD

**Issue by wuqingjing2010** [Hackerl/Wine_Appimage#34]
提示 (process:25253): GLib-CRITICAL **: 01:36:58.787: g_file_test: assertion 'filename != NULL' failed 是什么原因啊？

**Comment by wuqingjing2010** [comment]
命令行启动后 弹出 failed to register appimage in appimageLauncherFS: could not open map file

**Comment by Hackerl** [comment]
请提供系统环境，以及wine appimage版本

**Comment by Hackerl** [comment]
https://github.com/TheAssassin/AppImageLauncher/issues/130
这属于appimage本身的问题。
