### ISSUE TITLE
能否运行其他 windows 程序？

### ISSUE THREAD

**Issue by Laoyian** [Hackerl/Wine_Appimage#36]
打包好的 wine 程序如何使用其他 windows 软件？

**Comment by Hackerl** [comment]
可以。
如果需要运行其他程序，可以自己研究wine的环境打包。

https://www.cnblogs.com/x_wukong/p/4413932.html
https://forum.ubuntu.org.cn/viewtopic.php?t=72933
https://github.com/Hackerl/Wine_Appimage#%E6%9E%84%E5%BB%BAwindows-appimage%E5%BA%94%E7%94%A8
解包appimage：xxx.appimage --appimage-extract
