### ISSUE TITLE
Ubuntu18.04下报错缺少so文件

### ISSUE THREAD

**Issue by chinaliuhan** [Hackerl/Wine_Appimage#39]
直接运行文件没有反应.
通过命令行运行报错"ERROR: ld.so: object '/tmp/.mount_wineIUqzRW/bin/libhookexecv.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
"

不仅仅是微信,qq也是一样

**Comment by Hackerl** [comment]
这个报错属于正常情况

**Comment by chinaliuhan** [comment]
> 这个报错属于正常情况

正常? 可是这样没法用阿

**Comment by Hackerl** [comment]
不能使用和这个错误无关，请提供系统环境参数以及运行截图

**Comment by chinaliuhan** [comment]
# 环境参数
`
$ env
SESSION_MANAGER=local/nihao-ThinkPad-T480:@/tmp/.ICE-unix/3321,unix/nihao-ThinkPad-T480:/tmp/.ICE-unix/3321
XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/etc/xdg
LC_TELEPHONE=zh_CN.UTF-8
LANG=zh_CN.UTF-8
DISPLAY=:0
SHLVL=1
LOGNAME=nihao
LANGUAGE=zh_CN:zh:en_US:en
MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path
LC_NAME=zh_CN.UTF-8
XDG_VTNR=2
HOME=/home/nihao
VTE_VERSION=5202
XAUTHORITY=/run/user/1000/gdm/Xauthority
PWD=/home/nihao/AppImages
GIO_LAUNCHED_DESKTOP_FILE=/home/nihao/.config/autostart/guake.desktop
GTK_IM_MODULE=ibus
LC_NUMERIC=zh_CN.UTF-8
XDG_SESSION_ID=2
DESKTOP_AUTOSTART_ID=10895fa99062e26b41155983358755061400000033210019
DESKTOP_SESSION=ubuntu
IM_CONFIG_PHASE=2
XDG_SESSION_DESKTOP=ubuntu
DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path
USERNAME=nihao
TEXTDOMAIN=im-config
WINDOWPATH=2
LC_MEASUREMENT=zh_CN.UTF-8
LC_PAPER=zh_CN.UTF-8
GDMSESSION=ubuntu
LC_MONETARY=zh_CN.UTF-8
COLORTERM=truecolor
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
TEXTDOMAINDIR=/usr/share/locale/
CLUTTER_IM_MODULE=xim
LC_IDENTIFICATION=zh_CN.UTF-8
QT4_IM_MODULE=xim
XDG_DATA_DIRS=/usr/share/ubuntu:/usr/local/share:/usr/share:/var/lib/snapd/desktop
XDG_MENU_PREFIX=gnome-
GNOME_SHELL_SESSION_MODE=ubuntu
SHELL=/bin/zsh
QT_IM_MODULE=ibus
XDG_SESSION_TYPE=x11
LC_TIME=zh_CN.UTF-8
SSH_AGENT_PID=3401
GTK_MODULES=gail:atk-bridge
XDG_CURRENT_DESKTOP=ubuntu:GNOME
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/nihao/.composer/vendor/bin
TERM=xterm-256color
XDG_SEAT=seat0
USER=nihao
XMODIFIERS=@im=ibus
XDG_RUNTIME_DIR=/run/user/1000
LC_ADDRESS=zh_CN.UTF-8
GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1
GIO_LAUNCHED_DESKTOP_FILE_PID=3710
GUAKE_TAB_UUID=97522aab-0011-4163-8468-714bde11e983
QT_ACCESSIBILITY=1
OLDPWD=/home/nihao/AppImages
ZSH=/home/nihao/.oh-my-zsh
PAGER=less
LESS=-R
LC_CTYPE=zh_CN.UTF-8
LSCOLORS=Gxfxcxdxbxegedabagacad
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
_=/usr/bin/env

`

# 运行结果

`
~/AppImages ⌚ 2:45:05
$ ./Wechat-x86_64.AppImage 
wine: cannot find L"c:\\Program Files\\Tencent\\WeChat\\WeChatUpdate.exe"
wine: cannot find L"c:\\Program Files\\Tencent\\WeChat\\WeChatUpdate.exe"
Cleaning up

~/AppImages ⌚ 2:45:06
$ ERROR: ld.so: object '/tmp/.mount_winedgjU8A/bin/libhookexecv.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/tmp/.mount_winedgjU8A/bin/libhookexecv.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.


`

**Comment by Hackerl** [comment]
删除 $HOME/.Wechat、$HOME/.TIM 等相关文件夹后重新运行试试

**Comment by haotianfei** [comment]
同样的问题,删除相关文件夹也不行.
