### ISSUE TITLE
迅雷精简版任务添加后无法开始下载

### ISSUE THREAD

**Issue by Magnetic2014** [Hackerl/Wine_Appimage#4]
我安装了迅雷精简版并成功运行，但是添加了两个测试的下载任务（ed2k链接，windows系统里安装的迅雷可以下载）后，等了十分钟左右仍未开始下载，是什么问题呢？
之前有安装过wine，所以就直接用了以前安装好的。我下载了你的TIM，WeChat都可以正常使用，只有这个有点问题……
系统：Ubuntu 16.04 LTS
![image](https://user-images.githubusercontent.com/14221971/39526872-a9800fc8-4e52-11e8-99da-00f3def1664c.png)

**Comment by Magnetic2014** [comment]
Update: 重启也没有用，而且迅雷并没有创建下载文件……我下载的目录有读写权限

**Comment by Hackerl** [comment]
我这边从 Live CD 测试都通过了的，能否进行以下测试操作
1. 从命令行运行，提供终端输出信息
2. 提供当前 wine 版本
3. 更换其他链接进行下载测试

**Comment by Hackerl** [comment]
我这里下载 win10 1803 镜像满速

![screenshot from 2018-05-03 10-11-38](https://user-images.githubusercontent.com/15811751/39557468-e4114bc2-4e55-11e8-9d06-949fad507f0b.png)

**Comment by Magnetic2014** [comment]
1.命令行什么输出也没有……需要添加什么类似于--verbose的参数吗？
2.wine版本3.0
3.换了一个直链文件做下载测试正常，P2P还是不行，也许是我这里不能P2P？等我找一个其它的网络环境再测试一下

**Comment by Magnetic2014** [comment]
应该就是当时网络环境不支持P2P，更换网络环境后运行正常。
