### ISSUE TITLE
Ubuntu 16.04 WeChat聊天输入框无法输入和粘贴中文

### ISSUE THREAD

**Issue by sunskyhsh** [Hackerl/Wine_Appimage#41]
安装版本：
wine：https://github.com/Hackerl/Wine_Appimage/releases/download/continuous/Wine-x86_64-ubuntu.latest.AppImage
WeChat：https://github.com/Hackerl/Wine_Appimage/releases/download/appv2.0/Wechat-x86_64.AppImage
系统环境：
```
➜  uname -a
Linux UU 4.15.0-51-generic #55~16.04.1-Ubuntu SMP Thu May 16 09:24:37 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
➜  printenv |grep XMODIFIERS
XMODIFIERS=@im=fcitx
➜  locale
LANG=zh_CN.UTF-8
LANGUAGE=zh_CN:en_US:en
LC_CTYPE=zh_CN.UTF-8
LC_NUMERIC=en_US.UTF-8
LC_TIME=en_US.UTF-8
LC_COLLATE="zh_CN.UTF-8"
LC_MONETARY=en_US.UTF-8
LC_MESSAGES="zh_CN.UTF-8"
LC_PAPER=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_ALL=
```
运行Wechat-x86_64.AppImage的命令行输出：
```
➜  ./Wechat-x86_64.AppImage      
[0614/211129:ERROR:network_change_notifier_win.cc(158)] WSALookupServiceBegin failed with: 8
```

**Comment by Hackerl** [comment]
粘贴都不可以?

**Comment by Hackerl** [comment]
你用的版本是最新版的ubuntu，我正在添加16版本的支持。

**Comment by Hackerl** [comment]
16好像打包不成功，你可以试试我打包的别的版本

**Comment by sunskyhsh** [comment]
好的，谢谢！

**Comment by imxys** [comment]
作者您好，我使用的是KDE，同样的wine_x86_64，以及wechat，很高兴能够粘贴图片和文字（而且不用依靠deepin-wine），相比之下我自己在PlayOnLinux里面做的安装不知道少了什么库；如果可以的话望指教。

但中文同样是无法输入，推测基本上应该是解压AppImage打包以后运行wechat少了fcitx的相关环境变量。——不知道执行wechat的地方改成执行一个shell，然后在shell里面再导入一次fcitx相关环境变量是否可行。

**Comment by Hackerl** [comment]
输入法和环境变量关系不大，主要是各个发行版的libxi不兼容
输入法参考这个:https://github.com/Hackerl/Wine_Appimage/issues/10
粘贴参考这个:https://github.com/Hackerl/Wine_Appimage/issues/13

**Comment by imxys** [comment]
> 
> 
> 输入法和环境变量关系不大，主要是各个发行版的libxi不兼容
> 输入法参考这个:#10
> 粘贴参考这个:#13

谢谢！我多研究研究，以后也不用辛苦到处找其他人的打包可以自己做了
btw: #13这位似乎说话还非常英式，您帮了不少linux用户。。
