### ISSUE TITLE
黑色遮罩问题

### ISSUE THREAD

**Issue by AlessandroChen** [Hackerl/Wine_Appimage#48]
环境: Manjaro i3

问题: 有层灰色的遮罩，并且在我的各个工作区都会显示，大小和程序框一样

运行QQ时没有这类问题，只有微信会有

情况如图：

![DeepinScreenshot_termite_20190725194047](https://user-images.githubusercontent.com/36181635/61871818-557d6a00-af14-11e9-8bd2-15e8cf819a91.png)

![DeepinScreenshot_termite_20190725194032](https://user-images.githubusercontent.com/36181635/61871819-56160080-af14-11e9-856b-bbade95b80c5.png)

**Comment by Hackerl** [comment]
登陆成功后是否会出现

**Comment by AlessandroChen** [comment]
会的

**Comment by Hackerl** [comment]
应用层面的问题我很难去跟踪，太费时间了，而且应用并不是我关注的，我主要是针对wine的打包，你要是有兴趣可以自己研究一下。

**Comment by AlessandroChen** [comment]
好的，谢谢
