### ISSUE TITLE
CrossOver安装微信后的一些问题请教一下

### ISSUE THREAD

**Issue by pananfly** [Hackerl/Wine_Appimage#5]
我通过CrossOver上的TIM容器安装了微信（选择自己下载的微信安装包），中文字体通过复制宋体和黑体已经解决，现在问题是:1.输入文字在输入框中不显示，但是回车可以发送; 2.自带表情不能发送，收藏的和第三方的可以; 3.不能发送文件; 4.截图完没有用。请问你这边有什么解决思路没？

**Comment by Hackerl** [comment]
这涉及 wIne 环境的配置，比如发送文件时 wechat 会调用 ole32.dll 中的 OleCreateStaticFromData 函数。
wine 默认时将 OleCreateStaticFromData 转变为 Linux Api的调用，但是此函数未实现完全，所以无法成功发送文件。
不过 wine 提供调用 native dll 的功能，将 Windows xp 下的 ole32.dll 复制到 wine 环境中 ，然后配置调用 ole32.dll 时使用 原生dll。
我在打包的 wechat 中就是通过这样配置，修复了文件发送问题。

我直接使用的 askme765cs 的 TIM 配置，如果你看过他的配置，你就会发现配置 wine 很繁琐。
比如设置注册表以显示中文，配置 native dll 修复某些调用等等。
我不建议你手动配置，你可以直接使用我打包好的 Wechat，或者基于 TIM 的环境进行配置。

**Comment by pananfly** [comment]
恩，多谢回复，我主要是通过CrossOver就不用搞中文输入法的问题，设置了ibus相关的东西也不行我也有点郁闷，不过重在尝试嘛。多谢啦！
