### ISSUE TITLE
tim字体发虚

### ISSUE THREAD

**Issue by amazingfate** [Hackerl/Wine_Appimage#50]
https://www.cnblogs.com/mrway/p/10858234.html
https://wiki.winehq.org/Winecfg#Screen_Resolution_.28DPI_Setting.29
修改文件opt/TIM/system.reg即可
但是wine的窗口也相应放大了，字体只是显示大了，其实还是虚的
是不是内置的文泉驿字体导致的

**Comment by amazingfate** [comment]
把windows的字体放进去之后不发虚了，建议换一个显示好点的字体

**Comment by Hackerl** [comment]
多谢反馈
