### ISSUE TITLE
微信版本已经过期了

### ISSUE THREAD

**Issue by zoujiaqing** [Hackerl/Wine_Appimage#51]
腾讯屏蔽了旧版本微信登录。

**Comment by Hackerl** [comment]
麻烦提供具体截图

**Comment by zoujiaqing** [comment]
提示的意思就是：微信版本不受支持，请升级到最新版的微信客户端。

**Comment by probonopd** [comment]
仅使用开源聊天软件。不要信任封闭源代码软件。你永远不知道它是干什么的。 :+1

**Comment by zoujiaqing** [comment]
@probonopd thanks.

**Comment by holazt** [comment]
@zoujiaqing 自己将Appimage解包，然后放入最新版微信。

**Comment by bambuo** [comment]
Marking the AppImage as executable...
Embedding MD5 digest
Success

Please consider submitting your AppImage to AppImageHub, the crowd-sourced
central directory of available AppImages, by opening a pull request
at https://github.com/AppImage/appimage.github.io
lotuso@developer:~$ ls | grep WeChat
lotuso@developer:~$ '/home/lotuso/Desktop/Wechat-x86_64.AppImage' 
p11-kit: couldn't load module: /usr/lib/i386-linux-gnu/pkcs11/p11-kit-trust.so: /usr/lib/i386-linux-gnu/pkcs11/p11-kit-trust.so: 无法打开共享对象文件: 没有那个文件或目录
p11-kit: couldn't load module: /usr/lib/i386-linux-gnu/pkcs11/gnome-keyring-pkcs11.so: /usr/lib/i386-linux-gnu/pkcs11/gnome-keyring-pkcs11.so: 无法打开共享对象文件: 没有那个文件或目录
p11-kit: couldn't load module: /usr/lib/i386-linux-gnu/pkcs11/p11-kit-trust.so: /usr/lib/i386-linux-gnu/pkcs11/p11-kit-trust.so: 无法打开共享对象文件: 没有那个文件或目录
p11-kit: couldn't load module: /usr/lib/i386-linux-gnu/pkcs11/gnome-keyring-pkcs11.so: /usr/lib/i386-linux-gnu/pkcs11/gnome-keyring-pkcs11.so: 无法打开共享对象文件: 没有那个文件或目录
p11-kit: couldn't load module: /usr/lib/i386-linux-gnu/pkcs11/p11-kit-trust.so: /usr/lib/i386-linux-gnu/pkcs11/p11-kit-trust.so: 无法打开共享对象文件: 没有那个文件或目录
p11-kit: couldn't load module: /usr/lib/i386-linux-gnu/pkcs11/gnome-keyring-pkcs11.so: /usr/lib/i386-linux-gnu/pkcs11/gnome-keyring-pkcs11.so: 无法打开共享对象文件: 没有那个文件或目录
p11-kit: couldn't load module: /usr/lib/i386-linux-gnu/pkcs11/p11-kit-trust.so: /usr/lib/i386-linux-gnu/pkcs11/p11-kit-trust.so: 无法打开共享对象文件: 没有那个文件或目录
p11-kit: couldn't load module: /usr/lib/i386-linux-gnu/pkcs11/gnome-keyring-pkcs11.so: /usr/lib/i386-linux-gnu/pkcs11/gnome-keyring-pkcs11.so: 无法打开共享对象文件: 没有那个文件或目录
[1210/172757:INFO:exception_record.cc(518)] [QB]Process ID: 8 Type: 1
[1210/172757:ERROR:network_change_notifier_win.cc(156)] WSALookupServiceBegin failed with: 8

**Comment by ykla** [comment]
请更新

**Comment by citywalki** [comment]
+1，求助作者更新

**Comment by Hackerl** [comment]
我测试了: https://github.com/Hackerl/Wine_Appimage/releases/tag/appv2.0
微信可以登陆, 不能登陆的提供截图给我看看

**Comment by Hackerl** [comment]
试试更新的版本: https://github.com/Hackerl/Wine_Appimage/releases/download/appv2.0/Wechat-2.6.8.65-x86_64.AppImage

**Comment by citywalki** [comment]
> 试试更新的版本: https://github.com/Hackerl/Wine_Appimage/releases/download/appv2.0/Wechat-2.6.8.65-x86_64.AppImage
OK了，感谢！
