### ISSUE TITLE
Wechat Work 请求企业微信支持 2k 分辨率

### ISSUE THREAD

**Issue by ocian** [Hackerl/Wine_Appimage#53]
很好用,但是不能缩放
~~deepin 的能缩放,但是不好用~~

![screenshot_3](https://user-images.githubusercontent.com/18749280/70958194-65f4d380-20b3-11ea-958e-56cf9928f053.png)

**Comment by Hackerl** [comment]
```sh
***.appimage ----appimage-extract
```
解开appimage包之后, 里面就是普通的wine环境, 可以使用winecfg改变dpi.
https://github.com/wszqkzqk/deepin-wine-ubuntu/issues/45

**Comment by xcodebuild** [comment]
以 wechat 为例：

```
./Wechat-2.6.8.65-x86_64.AppImage --appimage-extract
WINEPREFIX='./squashfs-root/opt/Wechat/' wine winecfg
```

然后根据缩放调整 DPI，我这边是 4k，所以调整到 192

![image](https://user-images.githubusercontent.com/5436704/81203992-2e9fa880-8ffb-11ea-916c-aaa23273a0b7.png)

然后修改 `AppRun`

```
gedit squashfs-root/AppRun
```

把倒数第二行的 

```bash
export WINEPREFIX="$TOP_NODE"
```

改成 

```bash
export WINEPREFIX="$HERE/opt/Wechat/"
```

而后就可以用 

```
./squashfs-root/AppRun
```

来启动应用了

**Comment by Hackerl** [comment]
@xcodebuild WINEPREFIX不应该修改, appimage挂在出来的是只读目录.
你需要删除$HOME/.wechat目录, 重置虚拟目录读写节点.
