### ISSUE TITLE
请问哪里可以下载打包好的应用？

### ISSUE THREAD

**Issue by fgheng** [Hackerl/Wine_Appimage#54]
请问有没有打包好的应用呢？还是说每个应用都要自己去打包么？

**Comment by Hackerl** [comment]
releases 里面有我打包好的一些应用

**Comment by fgheng** [comment]
好的，谢谢您，我这里遇到了这个问题，您知道是什么原因么？我下午直接用wineappimage安装微信之后也是出现这个问题呢。
![image](https://user-images.githubusercontent.com/50551377/74335191-9cf71500-4dd6-11ea-963e-294d597eaf1a.png)

**Comment by Hackerl** [comment]
用的我打包的版本?

**Comment by fgheng** [comment]
> 用的我打包的版本?

是的，我这里出现了这个问题，我直接用您打包好的wine直接安装wechat.exe也是这个问题，我的系统是arch linux

**Comment by fgheng** [comment]
您好，更换成wine-ubuntu-latest问题解决了，一开始我下载的是wine-arch-latest

**Comment by Hackerl** [comment]
那个打包已经很久没更新了, 可能是因为 arch 更新太快, 打包的版本太旧了.

**Comment by Hackerl** [comment]
可以试试新打包的: https://github.com/Hackerl/Wine_Appimage/releases/tag/continuous
