### ISSUE TITLE
[问题]多个wineapp是使用同一个wine服务还是多个？

### ISSUE THREAD

**Issue by fgheng** [Hackerl/Wine_Appimage#55]
我同时开启qq和wechat，那么他们是各自使用各自的wine运行还是说两者是在同一个wine下运行呢？

**Comment by Hackerl** [comment]
我打包的应用是直接调用 "wine" 命令的, 将 "wine appimage" 重命名 "/usr/bin/wine" 即可, 所有的应用都会调用该程序.
"wine appimage" 会挂载出一个独立目录, 解压出程序文件到目录, 然后运行主程序.

**Comment by fgheng** [comment]
恩，谢谢您
