### ISSUE TITLE
哪里可以寻找安装包

### ISSUE THREAD

**Issue by fgheng** [Hackerl/Wine_Appimage#61]
您好，想请教一下您的微信的安装包是官网下载的么？为什么我自己本机安装wine之后从官网下载微信安装会出现一大堆问题，其中最严重的问题是输入框不能输入，输入英语之后看不到，汉语直接不能输入。我猜测应该是缺少某种dll，所以想请教下您您的微信是官网下载的还是从其他地方找的

**Comment by Hackerl** [comment]
自己要配置环境, 例如dll是调用原生的还是模拟层的, 中文字体也要自己配.

**Comment by Hackerl** [comment]
最好不要自己配, 有点麻烦.

**Comment by fgheng** [comment]
好的，谢谢你
