### ISSUE TITLE
运行QQ出现I require wine的错误提醒

### ISSUE THREAD

**Issue by mwmb2** [Hackerl/Wine_Appimage#66]
QQLight-x86_64.AppImage和Wine-x86_64-ubuntu.latest.AppImage都是从这里下载的。系统是Lubuntu 20.04。

两天前，系统还是Lubuntu19.10，QQ还一切正常运行。全新安装20.04后，给了QQ和Wine的AppImage执行权限，也做了/usr/bin/wine的链接，运行QQ就出现
I require wine.
You can download Wine-x86_64.AppImage from https://github.com/Hackerl/Wine_Appimage/releases.
Then run: chmod +x $(pwd)/Wine-x86_64.AppImage; sudo ln -s $(pwd)/Wine-x86_64.AppImage /usr/bin/wine

请问是什么原因呢？

**Comment by Hackerl** [comment]
直接运行 /usr/bin/wine 看看

**Comment by mwmb2** [comment]
问题解决了。ln的时候忘了$(pwd)。

谢谢作者及时的回复和伟大的工作！
