### ISSUE TITLE
fusermount: unknown option 'nonempty'

### ISSUE THREAD

**Issue by Anniywell** [Hackerl/Wine_Appimage#67]
OS: Debian GNU/Linux bullseye/sid x86_64
Kernel: 5.9.0-5-amd64
```bash
./ThunderMini-x86_64.AppImage 
fusermount: unknown option 'nonempty'

fusermount -V
fusermount3 version: 3.10.0
```

**Comment by Hackerl** [comment]
尝试解包: ./ThunderMini-x86_64.AppImage --appimage-extract
尝试运行: ./AppRun

**Comment by Anniywell** [comment]
> 尝试解包: ./ThunderMini-x86_64.AppImage --appimage-extract
> 尝试运行: ./AppRun

同样报“fusermount: unknown option 'nonempty'”，将AppRun中的nonempty移除后可以正常启动

**Comment by Hackerl** [comment]
可能是unionfs-fuse的版本差异
