### ISSUE TITLE
Appimage可以在arm架构上运行吗？

### ISSUE THREAD

**Issue by catcherxuefeng** [Hackerl/Wine_Appimage#68]
有没有在arm上运行x86wine的方案呢？

**Comment by Hackerl** [comment]
appimage只是一种软件打包的手段, 和wine没有关联, 在arm上运行wine需要wine官方的支持.
不过我猜测应该比较难, 因为大部分windows应用都是x86编译的, 除非wine可以完成x86->arm的指令转换, 否则很难运行应用.
