### ISSUE TITLE
OpenSUSE Tumbleweed 下 Wine.AppImage 无法正常运行

### ISSUE THREAD

**Issue by justrico** [Hackerl/Wine_Appimage#69]
系统是 OpenSUSE Tumbleweed 滚动更新发行版。我从 Continuous Build 中下载了 `Wine-x86_64-opensuse.latest.AppImage`，将其软链接到 `/usr/bin/wine` 后运行 `QQ-x86_64.AppImage` 报错：
```
/tmp/.mount_wineilGybK/AppRun:行18: /tmp/.mount_wineilGybK/lib/ld-linux.so.2: No such file or directory
Cleaning up
```
直接运行 `Wine-x86_64-opensuse.latest.AppImage` 也是相同的问题。
我尝试安装 `ld-linux.so.2` 结果告诉我有另外一个包提供了这个：
```
# sudo zypper in ld-linux.so.2
[sudo] root 的密码：
正在加载软件源数据...
正在读取已安装的软件包...
在软件包名中未找到 'ld-linux.so.2'。正在尝试在功能中查找。
已安装过了 'glibc-32bit'，其提供了 'ld-linux.so.2'。
正在解决软件包依赖关系...
无事可做。
```
请问有没有解决办法？感激不尽！

**Comment by Hackerl** [comment]
麻烦提供系统信息，你的系统是32位的?

**Comment by justrico** [comment]
不是，是64位的，OpenSUSE Tumbleweed 是 OpenSUSE 滚动更新发行版。包管理器是 `zypper` 和 `rpm`，桌面环境是 KDE 5.78.0 /Plasma 5.20.5

- `uname -a`
```
Linux localhost.localdomain 5.10.7-1-default #1 SMP Wed Jan 13 06:08:43 UTC 2021 (1c33a89) x86_64 x86_64 x86_64 GNU/Linux
```
- `cat /etc/os-release`
```
NAME="openSUSE Tumbleweed"
# VERSION="20210118"
ID="opensuse-tumbleweed"
ID_LIKE="opensuse suse"
VERSION_ID="20210118"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:tumbleweed:20210118"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Tumbleweed"
LOGO="distributor-logo"
```
- `neofetch`
![neofetch-myopensusevm.png](https://i.loli.net/2021/01/24/wOXqt1o3vIWyZfh.png)

**Comment by zengruipan** [comment]
manjaro也是，/tmp/.mount_wineNzCCdn/AppRun: line 18: /tmp/.mount_wineNzCCdn/usr/lib/ld-linux.so.2: No such file or directory

**Comment by Hackerl** [comment]
> manjaro也是，/tmp/.mount_wineNzCCdn/AppRun: line 18: /tmp/.mount_wineNzCCdn/usr/lib/ld-linux.so.2: No such file or directory

release里面的包很老了，建议自己clone用ci打包。

**Comment by Hackerl** [comment]
之前的打包有问题，尝试一下新版 https://github.com/Hackerl/Wine_Appimage/releases/tag/v3.0
