### ISSUE TITLE
第一次启动后 无法再次启动

### ISSUE THREAD

**Issue by zengruipan** [Hackerl/Wine_Appimage#70]
fusermount: failed to access mountpoint /tmp/.WXWork.unionfs: Permission denied

**Comment by zengruipan** [comment]
企业微信启动后。内存占满死机

**Comment by Hackerl** [comment]
企业微信只是我个人打包的测试版本，不进行维护

**Comment by Hackerl** [comment]
可以试试把"~/.WXWork"删除

**Comment by Hackerl** [comment]
尝试一下新版本 https://github.com/Hackerl/Wine_Appimage/releases/tag/v3.0

**Comment by zengruipan** [comment]
木有arch 呜呜

江湖风轻 ***@***.***> 于2021年3月28日周日 下午12:05写道：

**Comment by zengruipan** [comment]
manjaro的最好

pain pain ***@***.***> 于2021年3月29日周一 上午9:41写道：

**Comment by Hackerl** [comment]
有arch版本了
https://github.com/Hackerl/Wine_Appimage/releases/tag/v3.0
