### ISSUE TITLE
还会更新吗？包括windows的那些程序

### ISSUE THREAD

**Issue by mwmb2** [Hackerl/Wine_Appimage#71]
感谢作者！

**Comment by Hackerl** [comment]
暂时不会更新了，我相信以后原生的linux软件会越来越多，QQ、迅雷、百度网盘都有Linux版本了。

**Comment by mwmb2** [comment]
有没有让QQ能够视频的方法？

**Comment by Hackerl** [comment]
> 有没有让QQ能够视频的方法？

应该比较困难，我没有研究过。

**Comment by mwmb2** [comment]
听说deepin的wine+QQ可以视频。但我没有成功过，我用的是Ubuntu

**Comment by TsXor** [comment]
deepin wine有ubuntu移植（小声bb）

**Comment by Hackerl** [comment]
新版本：https://github.com/Hackerl/Wine_Appimage/releases/tag/v3.0

**Comment by mwmb2** [comment]
哇，有更新了！！！谢谢作者

**Comment by mwmb2** [comment]
> deepin wine有ubuntu移植（小声bb）

怎样才能QQ视频呢？按照网上的试了一圈都不行
