### ISSUE TITLE
看到仓库有 Arch Linux 的部署脚本，为什么没有 Arch 的发行包呢？

### ISSUE THREAD

**Issue by taotieren** [Hackerl/Wine_Appimage#72]
看到仓库有 Arch Linux 的部署脚本，为什么没有 Arch 的发行包呢？
或者提交到 AUR 仓库也会更好用。

**Comment by Hackerl** [comment]
docker打包有个bug，我一直没时间解决，你可以自己用脚本打包一个。

**Comment by taotieren** [comment]
刚才跑了下也看到类似的错误提示，

**Comment by Hackerl** [comment]
已修复: https://github.com/Hackerl/Wine_Appimage/commit/444203204632faadd1a88d460cf2437ae7175362
下载: https://github.com/Hackerl/Wine_Appimage/releases/tag/v3.0
