### ISSUE TITLE
能将发布的 Wine_Appimage 发不到 AUR 仓库吗？

### ISSUE THREAD

**Issue by taotieren** [Hackerl/Wine_Appimage#74]
能将发布的 Wine_Appimage 发不到 AUR 仓库吗？
或者 Arch Linux CN 的仓库？

**Comment by Hackerl** [comment]
放进仓库一般是arch软件包格式，或自动构建软件包的脚本，appimage不是很合适，这种单个打包的软件直接下载即可。

**Comment by taotieren** [comment]
好的等会写个 pkgbuild 提交上去2021年4月23日 10:12，江湖风轻 ***@***.***>写道：

放进仓库一般是arch软件包格式，或自动构建软件包的脚本，appimage不是很合适，这种单个打包的软件直接下载即可。

**Comment by taotieren** [comment]
已提交到 AUR 仓库
    https://aur.archlinux.org/packages/wine-appimage/

**Comment by de-conf** [comment]
> 已提交到 AUR 仓库
> https://aur.archlinux.org/packages/wine-appimage/

没见了，aur删除仓库了？

**Comment by taotieren** [comment]
被其他用户申请删除了社区管理员同意删除然后就没了需要重新提交吗？2021年5月22日 21:46，deconf ***@***.***>写道：



已提交到 AUR 仓库

https://aur.archlinux.org/packages/wine-appimage/



没见了，aur删除仓库了？

**Comment by de-conf** [comment]
> 被其他用户申请删除了社区管理员同意删除然后就没了需要重新提交吗？2021年5月22日 21:46，deconf ***@***.***>写道： 已提交到 AUR 仓库 https://aur.archlinux.org/packages/wine-appimage/ 没见了，aur删除仓库了？ —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

为啥会被申请删除？2333  建议只提交PKGBUILD？

**Comment by taotieren** [comment]
提交的理由说是和官方仓库的 wine 一样，没有必要装这个2021年5月23日 09:04，deconf ***@***.***>写道：



被其他用户申请删除了社区管理员同意删除然后就没了需要重新提交吗？2021年5月22日 21:46，deconf @.***>写道： 已提交到 AUR 仓库 https://aur.archlinux.org/packages/wine-appimage/ 没见了，aur删除仓库了？ —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.



为啥会被申请删除？2333  建议只提交PKGBUILD？
