### ISSUE TITLE
中文字体乱码

### ISSUE THREAD

**Issue by LethargyTeddy** [Hackerl/Wine_Appimage#76]
中文字体乱码，可以换字体吗？或者要怎么配置？

**Comment by Hackerl** [comment]
我将微软雅黑打包进去了，不应该会乱码，你下载使用的包是哪些

**Comment by LethargyTeddy** [comment]
> 我将微软雅黑打包进去了，不应该会乱码，你下载使用的包是哪些

Wine-x86_64-debian.sid.AppImage和qq还有dingding的安装程序
![截图_2021-12-08_21-59-52](https://user-images.githubusercontent.com/52397629/145221949-b082654a-41fe-4d92-a385-c9ff7ce8132e.png)
序
![截图_2021-12-08_22-01-10](https://user-images.githubusercontent.com/52397629/145221965-c3985868-7634-4651-b3e1-63fad1b84f52.png)

**Comment by Hackerl** [comment]
我提供了QQ的应用包，另外如果你需要从安装包安装应用，那么wine会创建一个全新的虚拟C盘文件系统，你需要在这个C盘里放入中文字体，具体参考wine教程。

**Comment by LethargyTeddy** [comment]
> 我提供了QQ的应用包，另外如果你需要从安装包安装应用，那么wine会创建一个全新的虚拟C盘文件系统，你需要在这个C盘里放入中文字体，具体参考wine教程。

您能给指个路吗？wine教程

**Comment by Hackerl** [comment]
google搜索一大堆，我也是半吊子

**Comment by LethargyTeddy** [comment]
> google搜索一大堆，我也是半吊子

您的qq应用包怎么下载？

**Comment by Hackerl** [comment]
https://github.com/Hackerl/Wine_Appimage/releases/tag/appv2.0
