### ISSUE TITLE
使用 TIM 成功 O\^o^/O

### ISSUE THREAD

**Issue by SenlinOS** [Hackerl/Wine_Appimage#8]
**系统：Lubuntu 18.04，64位**
下载了： TIM-x86_64.AppImage、Wine-x86_64.AppImage
1. 右键把它们的文件属性 -> 权限 -> 执行，改为：`任何人`
2. 建立Wine链接：
`sudo ln -s $(pwd)/Wine-x86_64.AppImage  /usr/bin/wine`
3. 双击运行 TIM-x86_64.AppImage，不成功多运行几次（我运行了两次）就成功了！

感谢开发的各位大神～辛苦了！

**(对了～现在不能直接使用 Fcitx 输入文字，我现在是用复制粘贴文字来用的～)**

**Comment by Hackerl** [comment]
不对呀，应该可以使用Fcitx输入的。
我是Debian9，可以使用搜狗输入法。

**Comment by SenlinOS** [comment]
@Hackerl 
* TIM发送图片打开目录后，文件夹中文名显示为乱码（TIM的界面是正常的）。
群通知～那里的中文消息也是乱码。
* 还有一个问题，点击TIM邮箱打开的是IE，不是系统浏览器！

**Comment by Hackerl** [comment]
在我的机器上没有发现乱码，这可能和TIM的wine环境配置相关。
因为这个环境配置我直接使用的别人的，所以不是很了解，我有空研究一下。

**Comment by Hackerl** [comment]
已经重新打包，可以试一试，邮箱问题已修复

**Comment by SenlinOS** [comment]
@Hackerl
TIM 的邮箱已经可以使用系统浏览器打开～Great！
(先用终端运行 TIM，会安装两个wine相关软件，之后就 OK)

**Comment by Hackerl** [comment]
那个是wine下.net环境，可以选择不装，不影响使用

**Comment by lgsen1996** [comment]
@SenlinOS @Hackerl 请问二位，输入法的问题解决了吗？需要怎么做？

**Comment by SenlinOS** [comment]
@lgsen1996 lgsen，没解决，用记事本复制粘贴吧！或者用手机QQ

**Comment by Hackerl** [comment]
ubuntu版本已发布，修复了输入法问题 -- https://github.com/Hackerl/Wine_Appimage/releases/download/v2.0/Wine-3.10-ubuntu-x86_64.AppImage

![image](https://user-images.githubusercontent.com/15811751/50679152-303f1200-103d-11e9-9d0a-a4976d8c9362.png)
