### ISSUE TITLE
自己根据最新版微信制作appimage的问题

### ISSUE THREAD

**Issue by mwmb2** [Hackerl/Wine_Appimage#81]
我将这里下载的微信appimage解压，然后用最新版的微信覆盖，然后重新打包成功。但是运行的时候提示当前微信版本需要windows7或更高的系统。我应该如何配置才能让最新版微信的appimage成功运行呢？

**Comment by Hackerl** [comment]
可以看看这里，https://askubuntu.com/questions/784279/can-wine-run-windows-7-apps

**Comment by mwmb2** [comment]
我的wine appimage也是这里下载的，如何打开wine configuration呢？

**Comment by Hackerl** [comment]
把 wine appimage 解开，里面有 winecfg 可执行程序：
```sh
WINEPREFIX=${path of wechat wine root} ./winecfg
```

**Comment by mwmb2** [comment]
不好意思，问题应该很低级
命令行执行了 WINEPREFIX=/home/****/Downloads/squashfs-root/
再执行./winecfg时，还是提示
./winecfg: 46: exec: ./wine: not found

**Comment by Hackerl** [comment]
```sh
export WINEPREFIX=/home/****/Downloads/squashfs-root/opt/Wechat/
export PATH=${dir of wine}:$PATH
./winecfg
```
WINEPREFIX要指定到具体文件夹，后面我忘了具体路径
